### ISSUE TITLE
[BUG] Bad Decrypt Error When Signing JWT Token

### ISSUE THREAD

**Issue by joemccann** [alkihis/archive-explorer-node#3]
First off, this project looks awesome.  There were a couple things I needed to do in order to get it up and running that weren't in the README, but overall, it's great.

Nonetheless, here's is a screencap video of me running locally and getting the following error after logging in:

[Screencap-Video.zip](https://github.com/alkihis/archive-explorer-node/files/3847754/Screencap-Video.zip)

```sh
Error: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt
    at Sign.sign (internal/crypto/sig.js:84:29)
    at Object.sign (/Users/joemccan-mbp/Documents/archive-explorer-node/node_modules/jwa/index.js:152:45)
    at jwsSign (/Users/joemccan-mbp/Documents/archive-explorer-node/node_modules/jws/lib/sign-stream.js:32:24)
    at SignStream.sign (/Users/joemccan-mbp/Documents/archive-explorer-node/node_modules/jws/lib/sign-stream.js:58:21)
    at SignStream.<anonymous> (/Users/joemccan-mbp/Documents/archive-explorer-node/node_modules/jws/lib/sign-stream.js:46:12)
    at Object.onceWrapper (events.js:299:28)
    at DataStream.emit (events.js:210:5)
    at DataStream.<anonymous> (/Users/joemccan-mbp/Documents/archive-explorer-node/node_modules/jws/lib/data-stream.js:32:12)
    at processTicksAndRejections (internal/process/task_queues.js:75:11) {
  opensslErrorStack: [
    'error:0907B00D:PEM routines:PEM_read_bio_PrivateKey:ASN1 lib',
    'error:2306A075:PKCS12 routines:PKCS12_item_decrypt_d2i:pkcs12 pbe crypt error',
    'error:23077074:PKCS12 routines:PKCS12_pbe_crypt:pkcs12 cipherfinal error'
  ],
  library: 'digital envelope routines',
  function: 'EVP_DecryptFinal_ex',
  reason: 'bad decrypt',
  code: 'ERR_OSSL_EVP_BAD_DECRYPT'
}
```

It appears to be an error in decrypting something during the signing call.

Any help would be appreciated!

Node Version: **12.13.0**
OS: MacOS: **10.14.6 Mojave**

**Comment by alkihis** [comment]
My bad, sorry for the late reply.

It's simply due to a change to the method used to sign/validate token. I just forgot to update README in order to reflect changes made to the verification process, sorry for that.

Changes were made in commit [ba50087](https://github.com/alkihis/archive-explorer-node/commit/ba50087ce45a8fd3732e6b5df0d4d208eb4d62ae).

You might need to install packages again and rebuild project.
